export const yesOrNo: string[] = ["YES", "NO"];

// BUILDING STRUCTURE
export const frameType: string[] = [
  "NOT APPLICABLE",
  "A - PROTECTED STEEL FRAME",
  "B - REINFORCED CONCRETE FRAME",
  "C - STEEL FRAME",
  "C - MASONRY",
  "D - FRAME",
  "S - PRE-ENGINEERED METAL",
];

export const ISOConstructionClass: string[] = [
  "NOT APPLICABLE",
  "1 - FRAME",
  "2 - JOISTED MASONRY",
  "3 - NON-COMBUSTIBLE",
  "4 - MASONRY NON-COMBUSTIBLE",
  "5 - MODIFIED FIRE RESISTIVE",
  "6 - FIRE RESISTIVE",
];

export const structuralFloorFrame: string[] = [
  "NONE",
  "WOOD",
  "STEEL",
  "CONCRETE",
  "CONCRETE & STEEL",
  "FIRE PROTECTED STEEL",
];

export const foundation: string[] = [
  "NONE",
  "FOOTING",
  "SLAB",
  "FOUNDATION WALLS",
  "FOUNDATION WALLS AND SLAB",
  "CRAWLSPACE & FOOTING",
  "REINFORCED CONCRETE FOOTINGS",
  "STILTS",
];

// BUILDING SERVICES SYSTEMS
export const serviceSystemsList: string[] = [
  "ELECTRICAL ONLY",
  "ELECTRICAL & PLUMBING",
  "ELECTRICAL,PLUMBING & HEATING",
  "ELECTRICAL, PLUMBING, HEATING & AIR CONDITIONING",
];

export const boilerAndPiping: string[] = [
  "Boiler & Piping Only",
  "Electric Baseboard or Wall Unit",
  "Forced Warm Air",
  "Gas, Oil, or Electric Suspended Unit Heaters",
  "Heat Pump",
  "Rooftop Unit",
  "Steam/Hot Water with Radiators",
  "Steam/Hot Water with Unit Heaters",
  "Thru-Wall Units",
  "Ventilation Only",
  "None",
];

export const chilledWaterSystem: string[] = [
  "Chilled Water w/ Air Handlers",
  "Chilled Water w/ Fan Coil Units",
  "Evaporative Coolers",
  "Forced Cool Air",
  "Heat Pump",
  "Rooftop Unit",
  "Thru-Wall Units",
  "Unit AC, Air Cooled",
  "Unit AC, Water Cooled",
  "None",
];

// ROOF DETAILS
export const roofCovering: string[] = [
  "Aluminum",
  "Built-up Smooth",
  "Built-up/Tar & Gravel",
  "Copper",
  "Fiberglass, Translucent Panel",
  "Metal Sandwich Panels",
  "Mineral Fiber",
  "Shakes, Wood",
  "Shingles, Asphalt",
  "Shingles, Fiberglass",
  "Single-Ply Membrane",
  "Slate",
  "Steel",
  "Steel, Porcelain Coated",
  "Tile, Clay",
  "Tile, Concrete",
  "Tin (Terne)",
  "None",
];

export const roofFrame: string[] = [
  "NOT APPLICABLE",
  "WOOD",
  "LIGHT GAUGE STEEL",
  "STEEL",
  "CONCRETE",
  "FIRE PROTECTED STEEL",
];

export const roofGeometry: string[] = [
  "FLAT",
  "PITCHED",
  "GABLE",
  "HIP",
  "MANSARD",
  "GAMBREL",
  "COMBINATION",
  "COMPLEX",
];

export const roofPitched: string[] = ["Flat", "Low", "Medium", "High"];

// EXTERIOR WALLS
export const exteriorWallsList: string[] = [
  "Adobe Block",
  "Brick on Frame",
  "Brick on Masonry",
  "Brick, Solid",
  'Brick, Solid, 18" thick',
  'Brick, Solid, 24" thick',
  "Concrete Block",
  "Concrete Block, Split Face",
  "Concrete, Poured in Place",
  "Concrete, Precast Panels",
  "Concrete, Tilt-up Panels",
  "Curtain Wall, Glass",
  "Curtain Wall, Granite",
  "EIFS on Masonry",
  "Glass Block",
  'Granite block, solid 24"',
  "Insulated Sandwich Panel",
  "Siding, Fiber Cement on Frame",
  "Siding, Fiber Cement on Masonry",
  "Siding, Metal/Other on Frame",
  "Siding, Metal/Other on Girts",
  "Siding, Metal/Other on Masonry",
  "Siding, Wood on Frame",
  "Siding, Wood on Masonry",
  "Stone on Frame",
  "Stone on Masonry",
  'Stone, Solid 12" thick',
  'Stone, Solid 18" thick',
  'Stone, Solid 24" thick',
  "Stucco on Frame",
  "Stucco on Masonry",
  "None",
];

// INTERIOR FINISHES

export const floorFinishes: string[] = [
  "Brick",
  "Carpet",
  "Concrete Sealer or Topping",
  "Epoxy",
  "Gratings",
  "Hardwood",
  "Hardwood Gym Floor",
  "Linoleum",
  "Laminated Wood",
  "Marble",
  "Pedestal",
  "Seamless",
  "Slate",
  "Synthetic Gym Floor",
  "Terrazo",
  "Tile, Asphalt",
  "Tile, Rubber",
  "Tile, Vinyl Composite",
  "Tile, Ceramic",
  "Tile, Tile Quarry",
  "Vinyl Sheet",
  "None",
];

export const ceilingFinishes: string[] = [
  "Cold Storage Insulation",
  "Drywall",
  "Drywall, Vinyl Covered",
  "Paint",
  "Paneling, Wood",
  "Plaster on Lath",
  "Plaster, Sprayed",
  "Plywood/Hardboard/Fiberboard",
  "Suspended Acoustical",
  "Textured Finish",
  "Tile, Accoustical",
  "Tile, Cork",
  "Tile, Metal",
  "Wallpaper, Vinyl",
  "None",
];

export const wallStructure: string[] = [
  "Brick, Solid",
  "Concrete Block",
  "Concrete, Poured in Place",
  "Demountable",
  "Folding",
  "Glass Block",
  "Glass Wall",
  "Studs/Girts",
  "Tile, Clay",
  "Wooven Wire",
  "None",
];

export const wallFinish: string[] = [
  "Cold Storage Insulation",
  "Drywall",
  "Epoxy",
  "Paint",
  "Paneling, Solid Wood",
  "Plaster on Lath",
  "Plaster, Sprayed",
  "Plywood/Hardboard/Fiberboard",
  "Sheetmetal",
  "Textured Finish",
  "Tile, Acoustical",
  "Tile, Ceramic",
  "Tile Quarry",
  "Wallpaper, Vinyl",
  "None",
];

export const fireSafety: string[] = [
  "FIRE SPRINKLER SYSTEM",
  "FIRE ALARMS ( MANUAL )",
  "FIRE ALARMS ( AUTOMATIC )",
  "SMOKE/HEAT DETECTORS",
  "FIRE EXTINGUESHERS",
  "EMERGENCY EXIT SIGNS/LIGHTINGS",
  "SECURITY CAMERAS/CCTV",
];

export const electricalQuality: string[] = ["High", "Low", "Average", "None"];
export const elevators: string[] = ["Passenger", "Freight"];

export const buildingUseList: string[] = [
  "1100 - APARTMENT, LOW RISE (1 TO 4 STORIES)",
  "1110 - APARTMENT, LOW RISE, OLDER",
  "1200 - APARTMENT, HIGH RISE (OVER 4 STORIES)",
  "1221 - APARTMENT, HIGH RISE, SHELL",
  "1222 - APARTMENT, HIGH RISE, INTERIOR SPACE",
  "1225 - LUXURY APARTMENT, HIGH RISE",
  "1230 - APARTMENT, 2-4 UNITS",
  "1300 - CONDOMINIUM",
  "1331 - CONDOMINIUM, SHELL",
  "1332 - CONDOMINIUM, INTERIOR SPACE",
  "1335 - CONDOMINIUM, WITHOUT INTERIOR FINISHES",
  "1340 - DELUXE CONDOMINIUM",
  "1350 - ROW HOUSE",
  "1440 - DORMITORY",
  "1445 - FRATERNITY HOUSE",
  "1450 - CONVENT OR RECTORY",
  "1455 - MANSION",
  "1460 - BED AND BREAKFAST",
  "1500 - HOTEL, FULL SERVICE",
  "1550 - HOTEL, LIMITED SERVICE",
  "1560 - HOTEL, OLDER",
  "1570 - LODGE",
  "1600 - MOTEL",
  "1610 - MOTEL, DOUBLE ROW",
  "1620 - MOTEL, SINGLE ROW",
  "1630 - MOTEL, EXTENDED STAY",
  "1640 - ROOMING HOUSE",
  "1645 - OFFICE - APARTMENT (MOTEL)",
  "2100 - OFFICE, LOW RISE (1 TO 4 STORIES)",
  "2121 - OFFICE, LOW RISE, SHELL",
  "2122 - OFFICE, LOW RISE, INTERIOR SPACE",
  "2124 - OFFICE, LOW RISE, OLDER",
  "2200 - OFFICE, MID RISE (5 TO 12 STORIES)",
  "2300 - OFFICE, HIGH RISE (12 OR MORE STORIES)",
  "2500 - BANK OR SAVINGS AND LOAN",
  "2510 - BANK (MINI OR BRANCH)",
  "2600 - CITY HALL OR COURTHOUSE",
  "2605 - GOVERNMENT COMMUNITY SERVICE BUILDING",
  "2650 - RADIO OR TV BROADCASTING CENTER",
  "2655 - MECHANICAL PENTHOUSE",
  "2660 - COMPUTER DATA CENTER",
  "3100 - STORE OR SHOP, GENERAL",
  "3102 - STORE OR SHOP, OLDER",
  "3105 - BARBER SHOP",
  "3110 - FLORIST SHOP",
  "3120 - BOOKSTORE",
  "3125 - DRUGSTORE",
  "3200 - DEPARTMENT STORE",
  "3215 - DISCOUNT DEPARTMENT STORE",
  "3300 - SHOPPING CENTER, STRIP TYPE",
  "3301 - SHOPPING CENTER, STRIP TYPE, SHELL",
  "3302 - SHOPPING CENTER, STRIP TYPE, INTERIOR SPACE",
  "3310 - SHOPPING CENTER, MALL TYPE",
  "3311 - SHOPPING CENTER, MALL TYPE, SHELL",
  "3312 - SHOPPING CENTER, MALL TYPE, INTERIOR SPACE",
  "3400 - STORE WITH OFFICES ABOVE",
  "3401 - STORE WITH APARTMENT ABOVE",
  "3500 - CONVENIENCE FOOD STORE",
  "3505 - SUPERMARKET",
  "3510 - WAREHOUSE FOOD STORE",
  "3600 - FURNITURE WAREHOUSE/SHOWROOM",
  "3700 - HOME IMPROVEMENT CENTER",
  "4100 - FAST FOOD WITHOUT SEATING",
  "4110 - FAST FOOD WITH SEATING",
  "4115 - DINING",
  "4120 - CAFETERIA",
  "4125 - BAR OR LOUNGE",
  "4200 - BOWLING CENTER",
  "4205 - CINEMA",
  "4206 - THEATER, LIVE STAGE",
  "4210 - CLUBHOUSE/RECREATION BUILDING",
  "4215 - COUNTRY CLUB",
  "4220 - COMMUNITY CENTER",
  "4225 - SENIOR CLUBHOUSE CENTER",
  "4230 - INDOOR TENNIS CLUB",
  "4232 - CITY CLUB",
  "4235 - HEALTH AND RACQUETBALL CLUB",
  "4240 - HEALTH CLUB",
  "4242 - FITNESS CENTER",
  "4245 - INDOOR ICE OR ROLLER RINK",
  "4300 - PARK RESTROOM BUILDING",
  "4305 - DRESSING AND SHOWER FACILITY",
  "4310 - ENCLOSED PARK PAVILION",
  "4315 - OPEN PARK PAVILION",
  "4320 - CONCESSION STAND",
  "4325 - CONCESSION STAND WITH PRESS BOX",
  "5100 - MEDICAL CLINIC",
  "5110 - HOSPITAL",
  "5120 - OUTPATIENT SURGICAL CENTER",
  "5125 - DISPENSARY",
  "5130 - DENTAL OFFICE/CLINIC",
  "5200 - NURSING HOME/CONVALESCENT CENTER",
  "5210 - HOME FOR THE ELDERLY",
  "5215 - MULTIPLE RESIDENCE, SENIOR CITIZEN",
  "5220 - MULTIPLE RESIDENCE, ASSISTED LIVING",
  "5225 - GROUP CARE HOME",
  "5230 - FUNERAL HOME",
  "5300 - VETERINARY CLINIC",
  "5305 - DOG KENNEL",
  "6100 - CHURCH, BASIC",
  "6105 - CHURCH, AVERAGE",
  "6110 - CHURCH, ELABORATE",
  "6115 - CHURCH, TRADITIONAL",
  "6120 - CHURCH, CONTEMPORARY",
  "6125 - CHURCH, CONTEMPORARY, HIGH",
  "6130 - CHURCH, CONTEMPORARY, MANSARD",
  "6135 - CHURCH, MODERN A-FRAME",
  "6140 - CHURCH, AUDITORIUM TYPE",
  "6142 - CHURCH, NARTHEX",
  "6145 - CHURCH WITH SUNDAY SCHOOL",
  "6148 - CHURCH, TOWER",
  "6150 - CHURCH CAMP DORMS",
  "6152 - CHURCH CAMP CABINS",
  "6155 - EDUCATIONAL WING",
  "6200 - FELLOWSHIP HALL",
  "6205 - FRATERNAL BUILDING",
  "6300 - ELEMENTARY SCHOOL",
  "6310 - JUNIOR HIGH SCHOOL",
  "6314 - HIGH SCHOOL",
  "6318 - SCHOOL, OLDER",
  "6321 - FINE ARTS / CRAFTS BUILDING (ELEMENTARY - HIGH SCHOOL)",
  "6322 - CLASSROOM (ELEMENTARY - HIGH SCHOOL)",
  "6324 - LECTURE CLASSROOM (ELEMENTARY - HIGH SCHOOL)",
  "6325 - LIBRARY / MEDIA CENTER (ELEMENTARY - HIGH SCHOOL)",
  "6326 - MANUAL ARTS BUILDING (ELEMENTARY - HIGH SCHOOL)",
  "6327 - MULTI-PURPOSE BUILDING (ELEMENTARY - HIGH SCHOOL)",
  "6329 - SCIENCE CLASSROOMS (ELEMENTARY - HIGH SCHOOL)",
  "6330 - GYMNASIUM (ELEMENTARY - HIGH SCHOOL)",
  "6340 - VOCATIONAL SCHOOL",
  "6345 - TECHNICAL TRADES BUILDING (COLLEGE)",
  "6400 - UNIVERSITY",
  "6402 - ADMINISTRATION BUILDING (UNIVERSITY OR TRADE SCHOOL)",
  "6404 - CLASSROOM (UNIVERSITY)",
  "6406 - LABORATORY (UNIVERSITY)",
  "6408 - LECTURE HALL (UNIVERSITY)",
  "6410 - LIBRARY (UNIVERSITY)",
  "6412 - ARTS AND CRAFTS BUILDING (COLLEGE)",
  "6414 - COMMONS (COLLEGE)",
  "6420 - PHYSICAL EDUCATION BUILDING",
  "6422 - FIELD HOUSE",
  "6424 - AUDITORIUM",
  "6426 - NATATORIUM",
  "6500 - PUBLIC LIBRARY",
  "6505 - FIRE STATION",
  "6506 - FIRE STATION, VOLUNTEER",
  "6510 - POLICE STATION OR JAIL",
  "6511 - JAIL / CORRECTIONAL FACILITY",
  "6515 - POST OFFICE",
  "6516 - POST OFFICE, BRANCH",
  "6517 - POST OFFICE, MAIN PROCESSING FACILITY",
  "6520 - AIR TERMINAL (SMALL REGIONAL)",
  "6522 - AIR TERMINAL (LARGE COMMERCIAL)",
  "6525 - ARMORY",
  "6530 - ATRIUM",
  "6531 - DINING ATRIUM",
  "6532 - CANOPY",
  "6540 - DAY CARE CENTER",
  "6550 - MUSEUM",
  "6560 - VISITOR CENTER",
  "7100 - SERVICE STATION",
  "7105 - TRUCK STOP",
  "7110 - AUTO REPAIR/SERVICE CENTER",
  "7115 - QUICK OIL CHANGE FACILITY",
  "7120 - CAR WASH",
  "7121 - CAR WASH, SELF-SERVE",
  "7122 - CAR WASH, AUTOMATIC",
  "7125 - SHOWROOM WITH SERVICE AREA",
  "7126 - SHOWROOM, AUTOMOBILE",
  "7130 - MARINA",
  "7131 - BOAT STORAGE BUILDING",
  "7140 - SERVICE SHOP",
  "7150 - AIRCRAFT HANGAR",
  "7151 - STORAGE HANGAR",
  "7152 - T-HANGAR",
  "7160 - LUMBER STORAGE FACILITY",
  "7165 - BUS TERMINAL",
  "7170 - TRUCK TERMINAL",
  "7175 - MUNICIPAL SERVICE GARAGE",
  "7180 - LAUNDROMAT",
  "7200 - PARKING STRUCTURE",
  "7300 - SELF-STORAGE FACILITY",
  "7310 - MINI-WAREHOUSE",
  "7315 - MINI-WAREHOUSE, HIGH RISE",
  "8100 - MANUFACTURING, LIGHT",
  "8101 - MANUFACTURING, POLE FRAME",
  "8200 - WAREHOUSE, LIGHT",
  "8201 - WAREHOUSE, POLE FRAME",
  "8210 - WAREHOUSE, HEAVY",
  "8215 - WAREHOUSE, MEGA",
  "8220 - WAREHOUSE, COLD STORAGE",
  "8221 - COLD STORAGE",
  "8300 - INDUSTRIAL MALL BUILDING",
  "8301 - INDUSTRIAL MALL BUILDING, INTERIOR SPACE",
  "8302 - INDUSTRIAL MALL BUILDING, SHELL",
  "8400 - UTILITY BUILDING",
  "8402 - UTILITY BUILDING, LIGHT COMMERCIAL",
  "8410 - BOILER HOUSE",
  "8500 - WHOLESALE",
  "8510 - INDUSTRIAL PARK BUILDING",
  "8515 - MANUFACTURING, HEAVY",
  "8516 - INDUSTRIAL MANUFACTURING, HEAVY",
  "8520 - OFFICE SERVICE CENTER BUILDING",
  "8525 - PRODUCTION LABORATORY",
  "8530 - HIGH TECH PRODUCTION FACILITY",
  "8535 - INDUSTRIAL FLEX BUILDING",
  "9000 - BAKERY",
  "9010 - BOTTLING PLANT",
  "9020 - CANNERY",
  "9030 - DAIRY",
  "9040 - LAUNDRY OR DRY CLEANING PLANT",
  "9050 - COMMERCIAL GREENHOUSE",
  "9060 - MEAT PACKING PLANT",
  "1000 - ADDITIONAL EQUIPMENT ONLY",
  "1001 - BASEMENT, UNFINISHED",
  "1002 - BASEMENT, PARTIALLY FINISHED",
  "1003 - BASEMENT, FINISHED",
  "1004 - BASEMENT, UNDERGROUND PARKING",
  "1005 - PARKING ON FIRST LEVEL",
];
